version: '3.8'
services:
  mongo:
    image: mongo:4.4
    restart: unless-stopped
    volumes:
        - mongodata:/data/db
    ports: 
      - 27017

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - ALGOLIA_APPLICATION_ID=${ALGOLIA_APPLICATION_ID}
      - ALGOLIA_API_KEY=${ALGOLIA_API_KEY}
    ports:
      - "3333:3333"
    restart: unless-stopped

  front:
    build:
      context: ./algolia-movies-front
      dockerfile: Dockerfile
    ports:
      - "80:80"

volumes:
    mongodata: